version: 0.2

env:
  variables:
    ACCOUNT_ID: "304534110140"
    REGION: "ap-south-1"
    CLUSTER: "mind-track-cluster"
    ECR_REPO: "mind-track-app"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo "Image Tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG .
      - echo "Pushing Docker image..."
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo "Update kubeconfig for cluster..."
      - aws eks update-kubeconfig --region $REGION --name $CLUSTER
      - echo "Updating Kubernetes manifests..."
      - sed -i "s|IMAGE_PLACEHOLDER|$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG|g" k8s/deployment.yaml
      - echo "Deploying to EKS..."
      - kubectl apply -f k8s/
